services:
  voiddex-api:
    image: voiddex-api:latest
    container_name: voiddex-api
    restart: always
    env_file:
      - .env.production
    ports:
      - "3013:3013"
    networks:
      - voiddex-network
    logging:
      driver: json-file
      options:
        max-size: "10m"
        max-file: "3"

networks:
  voiddex-network:
    name: voiddex-network
    external: true
